import { Question } from './types';

export const UNIVERSAL_QUESTIONS: Question[] = [
  {
    id: 'UQ1',
    question: 'What would you like to call this initiative?',
    fieldType: 'text',
    required: 'optional',
    category: 'meta',
  },
  {
    id: 'UQ2',
    question: 'Which type of initiative are you estimating?',
    fieldType: 'single-select',
    required: 'required',
    category: 'meta',
    options: [
      { label: 'Learning Initiative', score: 0 },
      { label: 'Project', score: 0 },
      { label: 'Program', score: 0 },
      { label: 'Change Initiative', score: 0 },
    ],
  },
  {
    id: 'UQ3',
    question: 'Where are you in the planning process?',
    fieldType: 'single-select',
    required: 'required',
    category: 'Scope / clarity risk',
    options: [
      { label: 'Early idea / not fully defined', score: 2 },
      { label: 'Initial planning started', score: 1 },
      { label: 'Scope is mostly defined', score: 0 },
      { label: 'Work is already in progress', score: 1 },
      { label: 'We are revising or rescuing an existing effort', score: 3 },
    ],
  },
  {
    id: 'UQ4',
    question: 'How would you describe the overall size of this initiative?',
    fieldType: 'single-select',
    required: 'required',
    category: 'Scope size',
    options: [
      { label: 'Very small: 1–2 deliverables, 1 workstream', score: 1 },
      { label: 'Small: 3–5 deliverables, 1–2 workstreams', score: 2 },
      { label: 'Medium: 6–15 deliverables, 2–4 workstreams', score: 3 },
      { label: 'Large: 16–30 deliverables, 4+ workstreams across multiple teams', score: 4 },
      { label: 'Enterprise / organization-wide: 30+ deliverables spanning 5+ functions or the full organization', score: 5 },
    ],
  },
  {
    id: 'UQ5',
    question: 'How complex is the work?',
    fieldType: 'single-select',
    required: 'required',
    category: 'Complexity level',
    options: [
      { label: 'Simple: 0–2 open questions, clear scope, 1 team executing', score: 1 },
      { label: 'Somewhat complex: 3–5 open questions or variables to resolve', score: 2 },
      { label: 'Moderately complex: 6–10 variables, 2–3 teams, some dependencies to manage', score: 3 },
      { label: 'Highly complex: 10–15 variables, 3–5 teams, significant ambiguity or interdependencies', score: 4 },
      { label: 'Very complex: 15+ variables, 5+ teams, or major unknowns across multiple risk areas', score: 5 },
    ],
  },
  {
    id: 'UQ6',
    question: 'How many stakeholder groups will need to provide input, review, or approval?',
    fieldType: 'single-select',
    required: 'required',
    category: 'Stakeholder and review complexity',
    options: [
      { label: 'One person or one small group', score: 0 },
      { label: '2–3 stakeholder groups', score: 1 },
      { label: '4–5 stakeholder groups', score: 2 },
      { label: '6 or more stakeholder groups', score: 3, isRiskFlag: true },
      { label: 'Executive, legal, compliance, or cross-functional approval required', score: 4, isRiskFlag: true },
    ],
  },
  {
    id: 'UQ7',
    question: 'How many review or approval cycles do you expect?',
    fieldType: 'single-select',
    required: 'required',
    category: 'Review / approval risk',
    options: [
      { label: 'One quick review', score: 0 },
      { label: 'Two review cycles', score: 1 },
      { label: 'Three review cycles', score: 2 },
      { label: 'Four or more review cycles', score: 3 },
      {
        label: 'Unknown or likely to change',
        score: 3,
        lowerConfidence: true,
        isUnknown: true,
        isCriticalRisk: true,
      },
    ],
  },
  {
    id: 'UQ8',
    question: 'How available are the people needed to provide information, make decisions, or approve the work?',
    fieldType: 'single-select',
    required: 'required',
    category: 'SME / decision-maker availability risk',
    options: [
      { label: 'Very available and responsive', score: 0 },
      { label: 'Somewhat available', score: 1 },
      { label: 'Limited availability', score: 2 },
      { label: 'Difficult to schedule', score: 3 },
      {
        label: 'Unknown or not yet identified',
        score: 3,
        lowerConfidence: true,
        isUnknown: true,
        isCriticalRisk: true,
      },
    ],
  },
  {
    id: 'UQ9',
    question: 'What materials or information already exist?',
    fieldType: 'single-select',
    required: 'required',
    category: 'Content / materials readiness risk',
    options: [
      { label: 'Strong existing materials are available', score: -1 },
      { label: 'Some useful materials are available', score: 0 },
      { label: 'Materials exist but need significant updates', score: 1 },
      { label: 'Very little exists', score: 2, isRiskFlag: true },
      { label: 'We are starting from scratch', score: 3, isRiskFlag: true },
    ],
  },
  {
    id: 'UQ10',
    question: 'How much timeline pressure exists?',
    fieldType: 'single-select',
    required: 'required',
    category: 'Timeline pressure risk',
    options: [
      { label: 'Flexible timeline', score: 0 },
      { label: 'Preferred deadline, but adjustable', score: 1 },
      { label: 'Important deadline', score: 2 },
      { label: 'Urgent deadline', score: 3 },
      {
        label: 'Deadline is fixed and cannot move',
        score: 4,
        lowerConfidence: true,
        isCriticalRisk: true,
      },
    ],
  },
  {
    id: 'UQ11',
    question: 'How polished does the final output need to be?',
    fieldType: 'single-select',
    required: 'required',
    category: 'Quality / compliance / accessibility risk',
    options: [
      { label: 'Quick working draft', score: -1 },
      { label: 'Internal-use quality', score: 0 },
      { label: 'Professional team-ready quality', score: 1 },
      { label: 'Executive-ready quality', score: 2 },
      { label: 'Client-facing, public-facing, or enterprise-level quality', score: 3 },
    ],
  },
  {
    id: 'UQ12',
    question: 'What level of launch or implementation support is needed?',
    fieldType: 'single-select',
    required: 'required',
    category: 'Implementation / rollout / handoff risk',
    options: [
      { label: 'No launch support needed', score: 0 },
      { label: 'Simple handoff only', score: 1 },
      { label: 'Basic rollout or communication support', score: 2 },
      { label: 'Coordinated launch support needed', score: 3 },
      { label: 'Full implementation, adoption, or rollout support needed', score: 4 },
    ],
  },
];

export const LEARNING_QUESTIONS: Question[] = [
  {
    id: 'LQ1',
    question: 'What type of learning output are you creating or updating?',
    fieldType: 'single-select',
    required: 'required',
    initiativeTypes: ['learning'],
    category: 'Scope size',
    options: [
      { label: 'Job aid, checklist, or quick-reference guide', score: 1 },
      { label: 'Microlearning asset', score: 2 },
      { label: 'Short training session or mini-workshop', score: 3 },
      { label: 'Full course or workshop', score: 4 },
      { label: 'Multi-module curriculum or learning path', score: 5 },
      { label: 'Blended learning experience', score: 5, extraComplexity: 1 },
      { label: 'Not sure yet', score: 3, lowerConfidence: true, isUnknown: true },
    ],
  },
  {
    id: 'LQ2',
    question: 'How will the learning be delivered?',
    fieldType: 'single-select',
    required: 'required',
    initiativeTypes: ['learning'],
    category: 'Delivery or production effort',
    options: [
      { label: 'PDF, worksheet, guide, or static resource', score: 1 },
      { label: 'Instructor-led training', score: 2 },
      { label: 'Virtual instructor-led training', score: 2 },
      { label: 'eLearning or self-paced course', score: 4 },
      { label: 'Video-based learning', score: 4 },
      { label: 'Blended format', score: 5 },
      { label: 'Multiple formats needed', score: 5, extraComplexity: 1 },
    ],
  },
  {
    id: 'LQ3',
    question: 'How much learning content needs to be created or updated?',
    fieldType: 'single-select',
    required: 'required',
    initiativeTypes: ['learning'],
    category: 'Scope size',
    options: [
      { label: 'Very small: one short asset or resource', score: 1 },
      { label: 'Small: one short lesson, module, or session', score: 2 },
      { label: 'Medium: one full course, workshop, or several assets', score: 3 },
      { label: 'Large: multiple modules, lessons, sessions, or resources', score: 4 },
      { label: 'Very large: full curriculum, learning path, or program-level set of assets', score: 5 },
      { label: 'Unknown or still being defined', score: 4, lowerConfidence: true, isUnknown: true },
    ],
  },
  {
    id: 'LQ4',
    question: 'How ready is the source content?',
    fieldType: 'single-select',
    required: 'required',
    initiativeTypes: ['learning'],
    category: 'Content / materials readiness risk',
    options: [
      { label: 'Content is approved and ready to use', score: -1 },
      { label: 'Content exists and needs light editing', score: 0 },
      { label: 'Content exists but needs restructuring', score: 1 },
      { label: 'Content exists but needs significant rewriting or validation', score: 3 },
      { label: 'Content does not exist yet', score: 4, isRiskFlag: true },
      { label: 'Content is changing or unstable', score: 4, lowerConfidence: true, isRiskFlag: true },
    ],
  },
  {
    id: 'LQ5',
    question: 'How much instructional design work is needed?',
    fieldType: 'single-select',
    required: 'required',
    initiativeTypes: ['learning'],
    category: 'Delivery or production effort',
    options: [
      { label: 'Minimal: organize existing content into a usable format', score: 1 },
      { label: 'Basic: add structure, objectives, and simple learner activities', score: 2 },
      { label: 'Moderate: create a complete learning flow with practice and reinforcement', score: 3 },
      { label: 'Advanced: design scenarios, activities, assessments, and application-based learning', score: 4 },
      {
        label: 'Extensive: design a full learning experience with multiple pathways, audiences, or performance outcomes',
        helperText: 'Multiple pathways, audiences, or performance outcomes',
        score: 5,
      },
      { label: 'Unknown', score: 3, lowerConfidence: true, isUnknown: true },
    ],
  },
  {
    id: 'LQ6',
    question: 'What level of learner interaction is needed?',
    fieldType: 'single-select',
    required: 'required',
    initiativeTypes: ['learning'],
    category: 'Delivery or production effort',
    options: [
      { label: 'Mostly informational', score: 1 },
      { label: 'Light interaction, such as reflection questions or knowledge checks', score: 2 },
      { label: 'Moderate interaction, such as practice activities, discussions, or exercises', score: 3 },
      {
        label: 'High interaction, such as scenarios, simulations, role plays, branching, or group activities',
        helperText: 'Scenarios, simulations, role plays, branching, or group activities',
        score: 4,
      },
      { label: 'Highly customized or complex interaction', score: 5 },
      { label: 'Not sure yet', score: 3, lowerConfidence: true, isUnknown: true },
    ],
  },
  {
    id: 'LQ7',
    question: 'What level of media or visual production is needed?',
    fieldType: 'single-select',
    required: 'required',
    initiativeTypes: ['learning'],
    category: 'Delivery or production effort',
    options: [
      { label: 'Minimal formatting only', score: 0 },
      { label: 'Basic visual design or slide/resource cleanup', score: 1 },
      { label: 'Custom graphics, diagrams, icons, or branded layouts', score: 2 },
      { label: 'Audio, video, animation, or AI-generated video required', score: 3 },
      { label: 'Multiple media types required', score: 4 },
      { label: 'Not sure yet', score: 2, lowerConfidence: true, isUnknown: true },
    ],
  },
  {
    id: 'LQ8',
    question: 'What level of assessment or practice is needed?',
    fieldType: 'single-select',
    required: 'conditional',
    initiativeTypes: ['learning'],
    category: 'Delivery or production effort',
    showWhen: [
      { questionId: 'LQ1', answerIndices: [3, 4, 5] }, // Full course, curriculum, blended
      { questionId: 'LQ2', answerIndices: [3, 4, 5, 6] }, // eLearning, video, blended, multiple
      { questionId: 'LQ5', answerIndices: [2, 3, 4] }, // Moderate, advanced, extensive
    ],
    options: [
      { label: 'No assessment or practice needed', score: 0 },
      { label: 'Simple knowledge checks', score: 1 },
      { label: 'Practice activities or discussion prompts', score: 2 },
      { label: 'Scenario-based questions or skill application exercises', score: 3 },
      { label: 'Formal assessment, certification, or pass/fail requirement', score: 4 },
      { label: 'Not sure yet', score: 2, lowerConfidence: true, isUnknown: true },
    ],
  },
  {
    id: 'LQ9',
    question: 'How many learner audiences or roles does this learning need to support?',
    fieldType: 'single-select',
    required: 'required',
    initiativeTypes: ['learning'],
    category: 'Scope size',
    options: [
      { label: 'One audience or role', score: 0 },
      { label: 'Two similar audiences or roles', score: 1 },
      { label: 'Multiple audiences with some differences', score: 2 },
      { label: 'Multiple audiences with different needs, examples, or workflows', score: 3 },
      {
        label: 'Many audiences, levels, regions, departments, or role-based pathways',
        helperText: 'Many audiences, levels, regions, departments, or role-based pathways',
        score: 4,
      },
      { label: 'Unknown or still being defined', score: 3, lowerConfidence: true, isUnknown: true },
    ],
  },
  {
    id: 'LQ10',
    question: 'What platform or technology requirements are involved?',
    fieldType: 'single-select',
    required: 'required',
    initiativeTypes: ['learning'],
    category: 'Platform or technology requirements',
    options: [
      { label: 'No platform or technology setup needed', score: 0 },
      { label: 'Simple file delivery or shared link', score: 1 },
      { label: 'Upload to LMS, LXP, intranet, or shared platform', score: 2 },
      { label: 'eLearning publishing, SCORM/xAPI, tracking, or testing required', score: 3 },
      { label: 'Multiple platforms, integrations, or technical reviews required', score: 4 },
      { label: 'Unknown or not yet confirmed', score: 3, lowerConfidence: true, isUnknown: true },
    ],
  },
  {
    id: 'LQ11',
    question: 'Are accessibility, compliance, legal, or policy requirements involved?',
    fieldType: 'single-select',
    required: 'required',
    initiativeTypes: ['learning'],
    category: 'Compliance, accessibility, or quality expectations',
    options: [
      { label: 'No special requirements', score: 0 },
      { label: 'Basic accessibility or formatting expectations', score: 1 },
      { label: 'Standard accessibility, brand, or internal policy review required', score: 2 },
      { label: 'Compliance, legal, HR, risk, or regulatory review required', score: 3, isRiskFlag: true },
      {
        label: 'Strict accessibility, compliance, audit, or regulatory requirements',
        score: 4,
        isRiskFlag: true,
        isCriticalRisk: true,
      },
      { label: 'Unknown or not yet confirmed', score: 3, lowerConfidence: true, isUnknown: true },
    ],
  },
  {
    id: 'LQ12',
    question: 'Will the learning need a pilot, facilitation preparation, or launch validation?',
    fieldType: 'single-select',
    required: 'conditional',
    initiativeTypes: ['learning'],
    category: 'Implementation / rollout / handoff risk',
    showWhen: [
      { questionId: 'LQ2', answerIndices: [1, 2, 5, 6] }, // ILT, VILT, blended, multiple formats
      { questionId: 'LQ1', answerIndices: [3, 4] }, // Full course, curriculum
      { questionId: 'LQ10', answerIndices: [2, 3, 4] }, // LMS/LXP, SCORM, multiple platforms
    ],
    options: [
      { label: 'No pilot or validation needed', score: 0 },
      { label: 'Quick internal review only', score: 1 },
      { label: 'Facilitator preparation or train-the-trainer needed', score: 2 },
      { label: 'Pilot session or learner testing needed', score: 3 },
      { label: 'Pilot, facilitator prep, revisions, and launch validation needed', score: 4 },
      { label: 'Unknown or not yet confirmed', score: 2, lowerConfidence: true, isUnknown: true },
    ],
  },
];

export const PROJECT_QUESTIONS: Question[] = [
  {
    id: 'PQ1',
    question: 'What is the primary deliverable for this project?',
    fieldType: 'single-select',
    required: 'required',
    initiativeTypes: ['project'],
    category: 'Scope size',
    options: [
      { label: 'Document, guide, checklist, or template', score: 1 },
      { label: 'Presentation, report, or recommendation', score: 2 },
      { label: 'Process, workflow, or procedure update', score: 3 },
      { label: 'Communication campaign or stakeholder-facing resource', score: 3 },
      { label: 'Tool, tracker, dashboard, or resource library', score: 4 },
      { label: 'Pilot, test, or proof of concept', score: 4 },
      { label: 'System, platform, or technology-related implementation support', score: 5, extraComplexity: 1 },
      { label: 'Not sure yet', score: 3, lowerConfidence: true, isUnknown: true },
    ],
  },
  {
    id: 'PQ2',
    question: 'How clearly is the project scope defined?',
    fieldType: 'single-select',
    required: 'required',
    initiativeTypes: ['project'],
    category: 'Scope / clarity risk',
    options: [
      { label: 'Very clear: goals, deliverables, and boundaries are defined', score: 0 },
      { label: 'Mostly clear: a few details still need confirmation', score: 1 },
      { label: 'Somewhat clear: direction is known, but scope needs refinement', score: 2 },
      { label: 'Unclear: stakeholders have different expectations', score: 3, lowerConfidence: true, isCriticalRisk: true },
      {
        label: 'Not defined yet',
        score: 4,
        lowerConfidence: true,
        isUnknown: true,
        isCriticalRisk: true,
      },
    ],
  },
  {
    id: 'PQ3',
    question: 'How many workstreams or major activity areas are involved?',
    fieldType: 'single-select',
    required: 'required',
    initiativeTypes: ['project'],
    category: 'Stakeholder and review complexity',
    options: [
      { label: 'One simple workstream', score: 1 },
      { label: 'Two workstreams', score: 2 },
      { label: 'Three to four workstreams', score: 3 },
      { label: 'Five or more workstreams', score: 4 },
      { label: 'Unknown or still being defined', score: 3, lowerConfidence: true, isUnknown: true },
    ],
  },
  {
    id: 'PQ4',
    question: 'How much work needs to be produced or completed?',
    fieldType: 'single-select',
    required: 'required',
    initiativeTypes: ['project'],
    category: 'Scope size',
    options: [
      { label: 'Very small: one simple deliverable or task set', score: 1 },
      { label: 'Small: a few related tasks or deliverables', score: 2 },
      { label: 'Medium: several deliverables or a moderate task set', score: 3 },
      { label: 'Large: many deliverables, tasks, or coordinated activities', score: 4 },
      { label: 'Very large: extensive deliverables, multiple layers, or significant coordination', score: 5 },
      { label: 'Unknown or still being defined', score: 4, lowerConfidence: true, isUnknown: true },
    ],
  },
  {
    id: 'PQ5',
    question: 'How many dependencies could affect the project timeline?',
    fieldType: 'single-select',
    required: 'required',
    initiativeTypes: ['project'],
    category: 'Dependency / governance risk',
    options: [
      { label: 'No major dependencies', score: 0 },
      { label: 'A few internal dependencies', score: 1 },
      { label: 'Several internal dependencies', score: 2 },
      { label: 'Internal and external dependencies', score: 3 },
      { label: 'Critical dependencies outside the project team\'s control', score: 4, lowerConfidence: true, isCriticalRisk: true },
      { label: 'Unknown', score: 3, lowerConfidence: true, isUnknown: true },
    ],
  },
  {
    id: 'PQ6',
    question: 'How available are the people needed to complete the project work?',
    fieldType: 'single-select',
    required: 'required',
    initiativeTypes: ['project'],
    category: 'SME / decision-maker availability risk',
    options: [
      { label: 'Dedicated resources are available', score: 0 },
      { label: 'Resources are available part-time', score: 1 },
      { label: 'Resources are limited or shared across other priorities', score: 2 },
      { label: 'Key resources are not confirmed', score: 3, lowerConfidence: true },
      { label: 'Resources are unknown or likely unavailable', score: 4, lowerConfidence: true, isUnknown: true },
    ],
  },
  {
    id: 'PQ7',
    question: 'How complex will decision-making be for this project?',
    fieldType: 'single-select',
    required: 'required',
    initiativeTypes: ['project'],
    category: 'Stakeholder and review complexity',
    options: [
      { label: 'One decision-maker with clear authority', score: 0 },
      { label: 'A small group can make decisions quickly', score: 1 },
      { label: 'Several people need to align before decisions are made', score: 2 },
      { label: 'Decisions require multiple layers of approval', score: 3 },
      { label: 'Decision authority is unclear', score: 4, lowerConfidence: true, isCriticalRisk: true },
      { label: 'Unknown', score: 3, lowerConfidence: true, isUnknown: true },
    ],
  },
  {
    id: 'PQ8',
    question: 'How much analysis, discovery, or research is needed before work can be completed?',
    fieldType: 'single-select',
    required: 'conditional',
    initiativeTypes: ['project'],
    category: 'Scope / clarity risk',
    showWhen: [
      { questionId: 'PQ1', answerIndices: [1, 2, 4, 5, 6] }, // Report, process, tool, pilot, tech
      { questionId: 'PQ2', answerIndices: [2, 3, 4] }, // Somewhat clear, unclear, not defined
    ],
    options: [
      { label: 'Minimal analysis needed', score: 0 },
      { label: 'Light discovery or information gathering', score: 1 },
      { label: 'Moderate analysis or stakeholder input needed', score: 2 },
      { label: 'Significant research, discovery, or current-state analysis needed', score: 3 },
      { label: 'Extensive analysis with unclear starting information', score: 4, lowerConfidence: true },
      { label: 'Unknown', score: 3, lowerConfidence: true, isUnknown: true },
    ],
  },
  {
    id: 'PQ9',
    question: 'What level of testing or validation is needed?',
    fieldType: 'single-select',
    required: 'conditional',
    initiativeTypes: ['project'],
    category: 'Review / approval risk',
    showWhen: [
      { questionId: 'PQ1', answerIndices: [4, 5, 6, 2] }, // Tool, pilot, tech, process
      { questionId: 'PQ12', answerIndices: [3, 4] }, // High visibility
    ],
    options: [
      { label: 'No testing or validation needed', score: 0 },
      { label: 'Quick internal check only', score: 1 },
      { label: 'Stakeholder validation needed', score: 2 },
      { label: 'User testing, pilot, or proof-of-concept validation needed', score: 3 },
      { label: 'Formal testing, QA, audit, or signoff required', score: 4, isRiskFlag: true },
      { label: 'Unknown', score: 2, lowerConfidence: true, isUnknown: true },
    ],
  },
  {
    id: 'PQ10',
    question: 'What needs to happen after the project deliverable is completed?',
    fieldType: 'single-select',
    required: 'required',
    initiativeTypes: ['project'],
    category: 'Implementation / rollout / handoff risk',
    options: [
      { label: 'Nothing; deliverable completion is the endpoint', score: 0 },
      { label: 'Simple handoff to one person or team', score: 1 },
      { label: 'Handoff with instructions, documentation, or walkthrough', score: 2 },
      { label: 'Rollout, communication, or training support needed', score: 3 },
      { label: 'Coordinated implementation across teams or functions needed', score: 4 },
      { label: 'Ongoing support, measurement, or post-launch updates needed', score: 5 },
      { label: 'Unknown', score: 3, lowerConfidence: true, isUnknown: true },
    ],
  },
  {
    id: 'PQ11',
    question: 'How likely is the project scope, direction, or deliverable to change during the work?',
    fieldType: 'single-select',
    required: 'required',
    initiativeTypes: ['project'],
    category: 'Scope / clarity risk',
    options: [
      { label: 'Unlikely to change', score: 0 },
      { label: 'Minor changes may happen', score: 1 },
      { label: 'Some changes are likely', score: 2 },
      { label: 'Significant changes are likely', score: 3, lowerConfidence: true },
      { label: 'Scope or direction is expected to evolve', score: 4, lowerConfidence: true, isCriticalRisk: true },
      { label: 'Unknown', score: 3, lowerConfidence: true, isUnknown: true },
    ],
  },
  {
    id: 'PQ12',
    question: 'What is the visibility or consequence level of this project?',
    fieldType: 'single-select',
    required: 'required',
    initiativeTypes: ['project'],
    category: 'Quality / compliance / accessibility risk',
    options: [
      { label: 'Low visibility; limited internal use', score: 0 },
      { label: 'Team-level visibility', score: 1 },
      { label: 'Department or function-level visibility', score: 2 },
      { label: 'Executive-facing or cross-functional visibility', score: 3 },
      { label: 'Client-facing, public-facing, regulatory, or enterprise-level visibility', score: 4 },
      { label: 'Unknown', score: 2, lowerConfidence: true, isUnknown: true },
    ],
  },
];

export const PROGRAM_QUESTIONS: Question[] = [
  {
    id: 'PRQ1',
    question: 'What type of program are you planning?',
    fieldType: 'single-select',
    required: 'required',
    initiativeTypes: ['program'],
    category: 'Scope size',
    options: [
      { label: 'Learning, training, or capability-building program', score: 3 },
      { label: 'Onboarding, academy, or role-based development program', score: 4 },
      { label: 'Business enablement or performance improvement program', score: 4 },
      { label: 'Process, operations, or workflow improvement program', score: 4 },
      { label: 'Technology, system, or tool rollout program', score: 5, extraComplexity: 1 },
      { label: 'Employee experience, customer experience, or culture-related program', score: 5, extraComplexity: 1 },
      { label: 'Transformation, change, or readiness program', score: 5, extraComplexity: 2 },
      { label: 'Not sure yet', score: 4, lowerConfidence: true, isUnknown: true },
    ],
  },
  {
    id: 'PRQ2',
    question: 'How many major workstreams are involved?',
    fieldType: 'single-select',
    required: 'required',
    initiativeTypes: ['program'],
    category: 'Stakeholder and review complexity',
    options: [
      { label: 'One main workstream', score: 1 },
      { label: 'Two workstreams', score: 2 },
      { label: 'Three to four workstreams', score: 3 },
      { label: 'Five to six workstreams', score: 4 },
      { label: 'Seven or more workstreams', score: 5 },
      { label: 'Unknown or still being defined', score: 4, lowerConfidence: true, isUnknown: true },
    ],
  },
  {
    id: 'PRQ3',
    question: 'How many major deliverables will the program include?',
    fieldType: 'single-select',
    required: 'required',
    initiativeTypes: ['program'],
    category: 'Scope size',
    options: [
      { label: 'One to two major deliverables', score: 1 },
      { label: 'Three to five major deliverables', score: 2 },
      { label: 'Six to ten major deliverables', score: 3 },
      { label: 'Eleven to twenty major deliverables', score: 4 },
      { label: 'More than twenty major deliverables', score: 5 },
      { label: 'Unknown or still being defined', score: 4, lowerConfidence: true, isUnknown: true },
    ],
  },
  {
    id: 'PRQ4',
    question: 'How many audiences, roles, or learner/user groups does the program need to support?',
    fieldType: 'single-select',
    required: 'required',
    initiativeTypes: ['program'],
    category: 'Scope size',
    options: [
      { label: 'One primary audience', score: 0 },
      { label: 'Two similar audiences', score: 1 },
      { label: 'Multiple audiences with some differences', score: 2 },
      { label: 'Multiple audiences with different needs, workflows, or expectations', score: 3 },
      {
        label: 'Many audiences, roles, levels, regions, departments, or pathways',
        helperText: 'Many audiences, roles, levels, regions, departments, or pathways',
        score: 4,
      },
      { label: 'Unknown or still being defined', score: 3, lowerConfidence: true, isUnknown: true },
    ],
  },
  {
    id: 'PRQ5',
    question: 'How many phases will the program require?',
    fieldType: 'single-select',
    required: 'required',
    initiativeTypes: ['program'],
    category: 'Stakeholder and review complexity',
    options: [
      { label: 'One phase', score: 1 },
      { label: 'Two phases', score: 2 },
      { label: 'Three phases', score: 3 },
      { label: 'Four or more phases', score: 4 },
      { label: 'Phases are needed but not yet defined', score: 4, lowerConfidence: true },
      { label: 'Unknown', score: 3, lowerConfidence: true, isUnknown: true },
    ],
  },
  {
    id: 'PRQ6',
    question: 'What level of governance will the program require?',
    fieldType: 'single-select',
    required: 'required',
    initiativeTypes: ['program'],
    category: 'Dependency / governance risk',
    options: [
      { label: 'Minimal governance; one owner can manage decisions', score: 0 },
      { label: 'Light governance; small working group needed', score: 1 },
      { label: 'Moderate governance; regular stakeholder check-ins needed', score: 2 },
      { label: 'Formal governance; steering group, sponsors, or decision forums needed', score: 3 },
      {
        label: 'Complex governance; multiple leadership groups, approval bodies, or escalation paths',
        helperText: 'Multiple leadership groups, approval bodies, or escalation paths',
        score: 4,
        lowerConfidence: true,
      },
      { label: 'Unknown or not yet defined', score: 3, lowerConfidence: true, isUnknown: true },
    ],
  },
  {
    id: 'PRQ7',
    question: 'How much cross-functional coordination is needed?',
    fieldType: 'single-select',
    required: 'required',
    initiativeTypes: ['program'],
    category: 'Stakeholder and review complexity',
    options: [
      { label: 'One team or function only', score: 0 },
      { label: 'Two to three teams or functions', score: 1 },
      { label: 'Several internal teams or functions', score: 2 },
      { label: 'Multiple internal teams plus external partners or vendors', score: 3 },
      {
        label: 'Enterprise-level coordination across many teams, regions, or business units',
        helperText: 'Many teams, regions, or business units',
        score: 4,
        lowerConfidence: true,
      },
      { label: 'Unknown or still being defined', score: 3, lowerConfidence: true, isUnknown: true },
    ],
  },
  {
    id: 'PRQ8',
    question: 'How many dependencies could affect the program timeline?',
    fieldType: 'single-select',
    required: 'required',
    initiativeTypes: ['program'],
    category: 'Dependency / governance risk',
    options: [
      { label: 'Few or no major dependencies', score: 0 },
      { label: 'A few internal dependencies', score: 1 },
      { label: 'Several internal dependencies', score: 2 },
      { label: 'Internal and external dependencies', score: 3 },
      { label: 'Critical dependencies outside the program team\'s control', score: 4, lowerConfidence: true, isCriticalRisk: true },
      { label: 'Unknown', score: 3, lowerConfidence: true, isUnknown: true },
    ],
  },
  {
    id: 'PRQ9',
    question: 'What level of pilot, testing, or validation is needed?',
    fieldType: 'single-select',
    required: 'conditional',
    initiativeTypes: ['program'],
    category: 'Review / approval risk',
    showWhen: [
      { questionId: 'PRQ10', answerIndices: [2, 3, 4] }, // Phased, coordinated, enterprise rollout
      { questionId: 'PRQ1', answerIndices: [4, 6] }, // Technology, transformation
      { questionId: 'PRQ6', answerIndices: [3, 4] }, // Formal, complex governance
    ],
    options: [
      { label: 'No pilot or validation needed', score: 0 },
      { label: 'Quick internal review only', score: 1 },
      { label: 'Stakeholder validation needed', score: 2 },
      { label: 'Pilot with a small group or limited audience needed', score: 3 },
      { label: 'Multi-phase pilot, testing, or validation needed', score: 4 },
      { label: 'Formal pilot, evaluation, approval, or readiness validation required', score: 5, isRiskFlag: true },
      { label: 'Unknown or not yet confirmed', score: 3, lowerConfidence: true, isUnknown: true },
    ],
  },
  {
    id: 'PRQ10',
    question: 'What type of rollout will the program require?',
    fieldType: 'single-select',
    required: 'required',
    initiativeTypes: ['program'],
    category: 'Implementation / rollout / handoff risk',
    options: [
      { label: 'Simple launch to one group', score: 1 },
      { label: 'Launch to one group with basic communications', score: 2 },
      { label: 'Phased rollout to multiple groups', score: 3 },
      { label: 'Coordinated rollout across teams, departments, or locations', score: 4 },
      { label: 'Enterprise, multi-region, or high-visibility rollout', score: 5, lowerConfidence: true },
      { label: 'Rollout strategy is not yet defined', score: 4, lowerConfidence: true, isCriticalRisk: true },
      { label: 'Unknown', score: 3, lowerConfidence: true, isUnknown: true },
    ],
  },
  {
    id: 'PRQ11',
    question: 'What level of measurement or reporting is expected?',
    fieldType: 'single-select',
    required: 'conditional',
    initiativeTypes: ['program'],
    category: 'Sustainment or reinforcement needs',
    showWhen: [
      { questionId: 'PRQ1', answerIndices: [1, 2, 4, 6] }, // Academy, enablement, tech, transformation
      { questionId: 'UQ11', answerIndices: [3, 4] }, // Executive, enterprise quality
      { questionId: 'UQ12', answerIndices: [3, 4] }, // Full implementation
    ],
    options: [
      { label: 'No formal measurement needed', score: 0 },
      { label: 'Basic completion, participation, or status tracking', score: 1 },
      { label: 'Standard reporting on progress, feedback, or usage', score: 2 },
      { label: 'Outcome measurement or performance indicators needed', score: 3 },
      { label: 'Dashboard, executive reporting, ROI, or impact evaluation needed', score: 4 },
      { label: 'Unknown or not yet defined', score: 2, lowerConfidence: true, isUnknown: true },
    ],
  },
  {
    id: 'PRQ12',
    question: 'What level of sustainment or ongoing management will be needed after launch?',
    fieldType: 'single-select',
    required: 'required',
    initiativeTypes: ['program'],
    category: 'Sustainment or reinforcement needs',
    options: [
      { label: 'None; program ends at launch', score: 0 },
      { label: 'Light post-launch support or updates', score: 1 },
      { label: 'Short-term reinforcement or follow-up needed', score: 2 },
      { label: 'Ongoing program management, updates, or communications needed', score: 3 },
      {
        label: 'Long-term sustainment, governance, reporting, or continuous improvement needed',
        helperText: 'Long-term sustainment, governance, reporting, or continuous improvement',
        score: 4,
      },
      { label: 'Unknown or not yet defined', score: 2, lowerConfidence: true, isUnknown: true },
    ],
  },
];

export const CHANGE_QUESTIONS: Question[] = [
  {
    id: 'CQ1',
    question: 'What type of change are you planning?',
    fieldType: 'single-select',
    required: 'required',
    initiativeTypes: ['change'],
    category: 'Adoption complexity',
    options: [
      { label: 'Process or workflow change', score: 3 },
      { label: 'System, platform, or technology change', score: 4 },
      { label: 'Policy, compliance, or procedure change', score: 4 },
      { label: 'Role, responsibility, or operating model change', score: 5 },
      { label: 'Behavior, culture, or mindset change', score: 5, extraComplexity: 1 },
      { label: 'Organizational restructuring or transformation', score: 5, extraComplexity: 2 },
      { label: 'Customer, employee, or stakeholder experience change', score: 4, extraComplexity: 1 },
      { label: 'Not sure yet', score: 4, lowerConfidence: true, isUnknown: true },
    ],
  },
  {
    id: 'CQ2',
    question: 'How many people or groups will be impacted by the change?',
    fieldType: 'single-select',
    required: 'required',
    initiativeTypes: ['change'],
    category: 'Scope size',
    options: [
      { label: 'Very small: one team or fewer than 25 people', score: 1 },
      { label: 'Small: 25–100 people', score: 2 },
      { label: 'Medium: 101–500 people', score: 3 },
      { label: 'Large: 501–2,500 people', score: 4 },
      { label: 'Very large: more than 2,500 people', score: 5 },
      { label: 'Enterprise-wide, multi-region, or external audience impact', score: 5, extraComplexity: 1 },
      { label: 'Unknown or still being defined', score: 4, lowerConfidence: true, isUnknown: true },
    ],
  },
  {
    id: 'CQ3',
    question: 'How much will people need to change what they do?',
    fieldType: 'single-select',
    required: 'required',
    initiativeTypes: ['change'],
    category: 'Adoption complexity',
    options: [
      { label: 'Minimal change: awareness only', score: 1 },
      { label: 'Small change: minor adjustment to current behavior', score: 2 },
      { label: 'Moderate change: people need to follow a new process or expectation', score: 3 },
      { label: 'Significant change: people need to learn new behaviors, tools, or responsibilities', score: 4 },
      { label: 'Major change: people need to change habits, mindset, workflow, or ways of working', score: 5, lowerConfidence: true },
      { label: 'Unknown or still being defined', score: 4, lowerConfidence: true, isUnknown: true },
    ],
  },
  {
    id: 'CQ4',
    question: 'How clearly have the impacts of the change been identified?',
    fieldType: 'single-select',
    required: 'required',
    initiativeTypes: ['change'],
    category: 'Impact and readiness clarity',
    options: [
      { label: 'Very clear: impacted groups, processes, tools, and behaviors are defined', score: 0 },
      { label: 'Mostly clear: a few impacts still need confirmation', score: 1 },
      { label: 'Somewhat clear: known at a high level, but more analysis is needed', score: 2 },
      { label: 'Unclear: impacts differ by group and are not fully understood', score: 3, lowerConfidence: true, isCriticalRisk: true },
      { label: 'Not assessed yet', score: 4, lowerConfidence: true, isCriticalRisk: true },
      { label: 'Unknown', score: 3, lowerConfidence: true, isUnknown: true },
    ],
  },
  {
    id: 'CQ5',
    question: 'How strong is leadership sponsorship for this change?',
    fieldType: 'single-select',
    required: 'required',
    initiativeTypes: ['change'],
    category: 'Sponsorship and alignment risk',
    options: [
      { label: 'Strong and visible sponsorship is already in place', score: 0 },
      { label: 'Sponsorship exists but needs more visibility', score: 1 },
      { label: 'Some leaders support it, but alignment is inconsistent', score: 2 },
      { label: 'Sponsorship is weak or unclear', score: 3, lowerConfidence: true, isCriticalRisk: true },
      { label: 'No clear sponsor has been identified', score: 4, lowerConfidence: true, isCriticalRisk: true },
      { label: 'Unknown', score: 3, lowerConfidence: true, isUnknown: true },
    ],
  },
  {
    id: 'CQ6',
    question: 'How aligned are key stakeholders on the change?',
    fieldType: 'single-select',
    required: 'required',
    initiativeTypes: ['change'],
    category: 'Sponsorship and alignment risk',
    options: [
      { label: 'Fully aligned on purpose, timing, and expectations', score: 0 },
      { label: 'Mostly aligned with minor open questions', score: 1 },
      { label: 'Some alignment, but key details are still being debated', score: 2 },
      { label: 'Stakeholders have different expectations or priorities', score: 3, lowerConfidence: true, isCriticalRisk: true },
      { label: 'Stakeholders are not aligned', score: 4, lowerConfidence: true, isCriticalRisk: true },
      { label: 'Unknown or not yet assessed', score: 3, lowerConfidence: true, isUnknown: true },
    ],
  },
  {
    id: 'CQ7',
    question: 'How much resistance do you expect?',
    fieldType: 'single-select',
    required: 'required',
    initiativeTypes: ['change'],
    category: 'Resistance and saturation risk',
    options: [
      { label: 'Low resistance expected', score: 0 },
      { label: 'Some questions or concerns expected', score: 1 },
      { label: 'Moderate resistance expected from some groups', score: 2 },
      { label: 'High resistance expected from key groups', score: 3, lowerConfidence: true, isCriticalRisk: true },
      { label: 'Significant resistance, fatigue, or distrust is likely', score: 4, lowerConfidence: true, isCriticalRisk: true },
      { label: 'Unknown or not yet assessed', score: 3, lowerConfidence: true, isUnknown: true },
    ],
  },
  {
    id: 'CQ8',
    question: 'How much other change is happening for the impacted audience?',
    fieldType: 'single-select',
    required: 'conditional',
    initiativeTypes: ['change'],
    category: 'Resistance and saturation risk',
    showWhen: [
      { questionId: 'CQ2', answerIndices: [2, 3, 4, 5] }, // Medium or larger audience
      { questionId: 'CQ3', answerIndices: [3, 4] }, // Significant or major behavior change
      { questionId: 'CQ7', answerIndices: [2, 3] }, // Moderate or high resistance
      { questionId: 'CQ1', answerIndices: [4, 5] }, // Behavior/culture, restructuring
    ],
    options: [
      { label: 'Little to no other change is happening', score: 0 },
      { label: 'Some other change is happening, but it is manageable', score: 1 },
      { label: 'Several changes are happening at the same time', score: 2 },
      { label: 'The audience is experiencing heavy change volume', score: 3, lowerConfidence: true },
      { label: 'The audience is already overwhelmed or fatigued', score: 4, lowerConfidence: true },
      { label: 'Unknown or not yet assessed', score: 3, lowerConfidence: true, isUnknown: true },
    ],
  },
  {
    id: 'CQ9',
    question: 'What level of communication support is needed?',
    fieldType: 'single-select',
    required: 'required',
    initiativeTypes: ['change'],
    category: 'Communication and enablement effort',
    options: [
      { label: 'Simple announcement only', score: 1 },
      { label: 'Basic communication plan with a few messages', score: 2 },
      { label: 'Multi-message communication plan for impacted groups', score: 3 },
      { label: 'Segmented communication plan by audience, role, or phase', score: 4 },
      { label: 'High-visibility communication campaign with leadership messaging', score: 5 },
      { label: 'Unknown or not yet defined', score: 3, lowerConfidence: true, isUnknown: true },
    ],
  },
  {
    id: 'CQ10',
    question: 'What level of training or enablement is needed?',
    fieldType: 'single-select',
    required: 'required',
    initiativeTypes: ['change'],
    category: 'Communication and enablement effort',
    options: [
      { label: 'No training or enablement needed', score: 0 },
      { label: 'Simple job aid, FAQ, or quick reference needed', score: 1 },
      { label: 'Brief training, demo, or walkthrough needed', score: 2 },
      { label: 'Role-based training or manager enablement needed', score: 3 },
      { label: 'Full learning experience, curriculum, or capability-building support needed', score: 4, extraComplexity: 1 },
      { label: 'Unknown or not yet defined', score: 3, lowerConfidence: true, isUnknown: true },
    ],
  },
  {
    id: 'CQ11',
    question: 'What level of readiness work is needed before launch?',
    fieldType: 'single-select',
    required: 'conditional',
    initiativeTypes: ['change'],
    category: 'Impact and readiness clarity',
    showWhen: [
      { questionId: 'CQ1', answerIndices: [1, 3, 5] }, // Tech, operating model, restructuring
      { questionId: 'CQ14', answerIndices: [2, 3] }, // Moderate or significant disruption
      { questionId: 'UQ12', answerIndices: [3, 4] }, // Full implementation
    ],
    options: [
      { label: 'No formal readiness work needed', score: 0 },
      { label: 'Basic readiness check needed', score: 1 },
      { label: 'Stakeholder or manager readiness activities needed', score: 2 },
      { label: 'Audience readiness assessment or feedback activities needed', score: 3 },
      { label: 'Formal readiness plan with go/no-go criteria needed', score: 4 },
      { label: 'Unknown or not yet defined', score: 2, lowerConfidence: true, isUnknown: true },
    ],
  },
  {
    id: 'CQ12',
    question: 'What level of reinforcement or adoption support is needed after launch?',
    fieldType: 'single-select',
    required: 'required',
    initiativeTypes: ['change'],
    category: 'Reinforcement and measurement effort',
    options: [
      { label: 'No post-launch reinforcement needed', score: 0 },
      { label: 'Light follow-up communication only', score: 1 },
      { label: 'Short-term reinforcement, reminders, or manager support needed', score: 2 },
      { label: 'Ongoing office hours, coaching, reporting, or support needed', score: 3 },
      {
        label: 'Long-term adoption support, behavior reinforcement, or continuous improvement needed',
        helperText: 'Long-term adoption support, behavior reinforcement, or continuous improvement',
        score: 4,
      },
      { label: 'Unknown or not yet defined', score: 2, lowerConfidence: true, isUnknown: true, isCriticalRisk: true },
    ],
  },
  {
    id: 'CQ13',
    question: 'What level of adoption measurement is expected?',
    fieldType: 'single-select',
    required: 'conditional',
    initiativeTypes: ['change'],
    category: 'Reinforcement and measurement effort',
    showWhen: [
      { questionId: 'CQ1', answerIndices: [1, 2] }, // Policy, tech change
      { questionId: 'UQ11', answerIndices: [3, 4] }, // Executive, enterprise quality
      { questionId: 'CQ12', answerIndices: [3, 4] }, // Long-term adoption
    ],
    options: [
      { label: 'No formal adoption measurement needed', score: 0 },
      { label: 'Basic completion, participation, or communication tracking', score: 1 },
      { label: 'Feedback or pulse-check measurement needed', score: 2 },
      { label: 'Adoption, usage, compliance, or behavior indicators needed', score: 3 },
      { label: 'Executive reporting, dashboard, ROI, or impact evaluation needed', score: 4 },
      { label: 'Unknown or not yet defined', score: 2, lowerConfidence: true, isUnknown: true },
    ],
  },
  {
    id: 'CQ14',
    question: 'How much disruption could this change create for day-to-day work?',
    fieldType: 'single-select',
    required: 'required',
    initiativeTypes: ['change'],
    category: 'Operational disruption risk',
    options: [
      { label: 'Minimal disruption expected', score: 0 },
      { label: 'Some temporary disruption expected', score: 1 },
      { label: 'Moderate disruption to workflows, roles, or routines', score: 2 },
      {
        label: 'Significant disruption to operations, productivity, or customer/employee experience',
        helperText: 'Significant impact on operations, productivity, or experience',
        score: 3,
        lowerConfidence: true,
        isCriticalRisk: true,
      },
      {
        label: 'High disruption with business, compliance, customer, or workforce risk',
        helperText: 'High risk to business, compliance, customers, or workforce',
        score: 4,
        lowerConfidence: true,
        isCriticalRisk: true,
      },
      { label: 'Unknown or not yet assessed', score: 3, lowerConfidence: true, isUnknown: true },
    ],
  },
];

export const ALL_QUESTIONS: Question[] = [
  ...UNIVERSAL_QUESTIONS,
  ...LEARNING_QUESTIONS,
  ...PROJECT_QUESTIONS,
  ...PROGRAM_QUESTIONS,
  ...CHANGE_QUESTIONS,
];

export function getQuestionsForInitiative(type: string): Question[] {
  const pathMap: Record<string, Question[]> = {
    learning: LEARNING_QUESTIONS,
    project: PROJECT_QUESTIONS,
    program: PROGRAM_QUESTIONS,
    change: CHANGE_QUESTIONS,
  };
  return [...UNIVERSAL_QUESTIONS, ...(pathMap[type] ?? [])];
}
